#this is to push image to docker hub
---
- name: To create docker image and push it docker hub
  hosts: localhost
  #vars:
   # WORK
  tasks: 
    - name: this will check whether directoryexist
      stat:
        path: '{{ WORK }}/docker'
      register: p
    - debug :
        var: p
  
    - name: this will clone Docker directory when docker dir doesnt exist
      git:  
        repo: https://github.com/bmitesh1/hello-world.git
        clone: yes
        dest: '{{ WORK }}/docker'
      when: not p.stat.exists
    - name: To update the docker file
      git:
        repo: https://github.com/bmitesh1/hello-world.git
        dest: '{{ WORK }}/docker'
        update: yes 
      when: p.stat.exists
    - name: this task will create docker image from Dockerfile
      docker_image: 
        name: bmitesh/devops1
        path: '{{ WORK }}/docker'
        push: yes
      #state: present 
          
    

